---
title: "R Notebook"
output: html_notebook
---


```{r}
library(ggplot2)
library(tidyverse)
library(glue)

dati <- read_csv("./healthcare-dataset-stroke-data.csv")
```

```{r}
print("Prime righe del dataset:")
print(head(dati,5))
```
```{r}
print(glue("Are the patient all different: {dim(dati)[1] == length(unique(dati$id))}"))
```
```{r}
print("Riepilogo del dataset:")
print(summary(dati))
```
```{r}
print("Nome delle colonne disponibili:")
print(colnames(dati))
```
```{r}
# Missing values
na_count <- sapply(dati, function(x) sum(x == "N/A"))

# Stampa i risultati
print("Conteggio di 'N/A' per colonna:")
print(na_count)
```

```{r}
print("Statistiche descrittive per le variabili numeriche:")
print(summary(select(dati, where(is.numeric))))
```
```{r}
print("Frequenze per le variabili categoriche:")
print(table(dati$gender)) # Cambia 'gender' con il nome della colonna appropriata
```
```{r}
print(paste("Righe prima della pulizia:", nrow(dati)))

dati_puliti <- dati[!apply(dati == "N/A", 1, any), ]

print(paste("Righe dopo la pulizia:", nrow(dati_puliti)))
```
```{r}

```
```{r}
dati_puliti$bmi <- as.numeric(as.character(dati_puliti$bmi))
```
```{r}
colnames(dati_puliti)
```
```{r}
pdf("Istogrammi_per_colonna.pdf", width = 11, height = 8.5)

for (colonna in c('age','bmi','avg_glucose_level')) {
  # Controllare se la colonna è numerica
  if (is.numeric(dati_puliti[[colonna]])) {

    p <- ggplot(dati_puliti, aes(x = !!sym(colonna))) +
      geom_histogram(bins = 30, fill = "blue", color = "black") +
      labs(title = paste("Istogramma di", colonna), x = colonna, y = "Frequenza") +
      theme_minimal()
    print(p)
  }
}
dev.off()
```
```{r}
pdf("Boxplots_per_colonna.pdf", width = 11, height = 8.5)

# Generare un box plot per ogni colonna numerica
for (colonna in c('age','bmi','avg_glucose_level')) {

  if (is.numeric(dati_puliti[[colonna]])) {

    p <- ggplot(dati_puliti, aes(x = factor(0), y = !!sym(colonna))) +
      geom_boxplot() +
      labs(title = paste("Box plot di", colonna), y = colonna, x = "") +
      theme_minimal()
    print(p)
  }
}
dev.off()
```

```{r}
df <- dati_puliti
df
```

CLASSIFICATION OF STROKES
```{r}
install.packages('tidymodels')
install.packages('caret')  # stratified split
library(tidymodels)
```


```{r}
df <- select(df, -1) # removing the id
```


```{r}



library(caret)
train.index <- createDataPartition(df$stroke, p = 0.75, list = FALSE)
df_train <- df[ train.index,]
df_test  <- df[-train.index,]

train_2.index <- createDataPartition(df_train$stroke, p = 0.75, list = FALSE)
df_val  <- df_train[-train_2.index,]
df_train <- df_train[ train_2.index,]

print(glue("Train set shape: ({dim(df_train)[[1]]}, {dim(df_train)[[2]]})"))
print(glue("Validation set shape: ({dim(df_val)[[1]]}, {dim(df_val)[[2]]})"))
print(glue("Test set shape: ({dim(df_test)[[1]]}, {dim(df_test)[[2]]})"))


```



```{r}
# LOGISTIC REG

base_recipe <- recipe(stroke ~ ., data = df_train)

logreg <- logistic_reg() %>% set_engine('glm')

 stroke_recipe <- base_recipe %>% step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors())
 
 logreg_workflow <- workflow() %>% add_model(logreg) %>% add_recipe(stroke_recipe)
 
logreg_fit_workflow <- logreg_workflow %>% fit(df_train)  

logreg_fit_workflow
```
```{r}
logreg_fit_workflow %>% extract_fit_engine() %>% summary()
```

```{r}
logreg_trainPred <- logreg_fit_workflow %>% augment(df_train)
logreg_trainPred %>% head(2)
```

```{r}
yardstick::metrics(logreg_trainPred, truth=stroke, estimate=.pred_class)
```

```{r}
logreg_trainPred %>% group_by(stroke) %>% 
  summarise(n=n()) %>% mutate(freq=n/sum(n))
```


```{r}
logreg_cm <- logreg_trainPred %>% 
  conf_mat(truth=stroke,estimate=.pred_class)

logreg_cm
```

```{r}
yardstick::recall(logreg_trainPred, truth=stroke,estimate=.pred_class,event_level='second')
```

```{r}
yardstick::recall(logreg_trainPred, truth=stroke,estimate=.pred_class,event_level='second')
roc_curve(logreg_trainPred, stroke,.pred_1,event_level = 'second') %>% autoplot()
```
RF

```{r}
yardstick::recall(logreg_trainPred, truth=stroke,estimate=.pred_class,event_level='second')
roc_curve(logreg_trainPred, stroke,.pred_1,event_level = 'second') %>% autoplot()
rand_forest_spec <- rand_forest(mtry = 3) %>%  
  set_engine('randomForest') %>% 
  set_mode('classification')
```

```{r}
install.packages('randomForest')


rf <- rand_forest(mtry = 3) %>%  
  set_engine('randomForest') %>% 
  set_mode('classification') 


 rf_workflow <- workflow() %>% add_model(rf) %>% add_recipe(stroke_recipe)
 
 
rf_fit_workflow <- rf_workflow %>% fit(df_train)  


logreg_fit_workflow
```
```{r}
rf_trainPred <- rf_fit_workflow %>% augment(df_train)
rf_trainPred %>% head(300)
```

```{r}
yardstick::metrics(rf_trainPred, truth=stroke, estimate=.pred_class)

rf_cm <- rf_trainPred %>% 
  conf_mat(truth=stroke,estimate=.pred_class)

rf_cm

yardstick::recall(rf_trainPred, truth=stroke,estimate=.pred_class,event_level='second')
```
```{r}
roc_curve(rf_trainPred, stroke,.pred_1,event_level = 'second') %>% autoplot()
```



```{r}
    threshold <- 0.2
    pred_class <- ifelse(rf_trainPred$.pred_1 > threshold, 1, 0)


    rf_trainPred$.pred_class <- as.factor(as.numeric(pred_class))
```

```{r}
rf_cm <- rf_trainPred %>% 
  conf_mat(truth=stroke,estimate=.pred_class)

print(rf_cm)

yardstick::recall(rf_trainPred, truth=stroke,estimate=.pred_class,event_level='second')
```
```{r}
class(tb_train$stroke)
```


```{r}
logreg_lasso <- logistic_reg(penalty = tune(), mixture = 1) %>% set_engine('glmnet')


 logreg_lasso_workflow <- workflow() %>% add_model(logreg_lasso) %>% add_recipe(stroke_recipe)
 
logreg_lasso__fit_workflow <- logreg_lasso_workflow %>% fit(tb_train)  

logreg_lasso_fit_workflow
```

```{r}
logreg_ridge <- logistic_reg(penalty = tune(), mixture = 2) %>% set_engine('glmnet')


 logreg_ridge_workflow <- workflow() %>% add_model(logreg_ridge) %>% add_recipe(stroke_recipe)
 
logreg_ridge__fit_workflow <- logreg_ridge_workflow %>% fit(tb_train)  

logreg_ridge_fit_workflow
```


```{r}
base_recipe_reg <- recipe(bmi ~ ., data = tb_train)

linreg <-  linear_reg() %>% set_engine("lm")

 bmi_recipe <- base_recipe_reg %>% step_normalize(all_numeric_predictors()) %>%
  step_dummy(all_nominal_predictors())
 
 linreg_workflow <- workflow() %>% add_model(linreg) %>% add_recipe(bmi_recipe)
 
linreg_fit_workflow <- linreg_workflow %>% fit(tb_train)

linreg_fit_workflow
```



```{r}

linreg_lasso <-  linear_reg(penalty = tune(), mixture = 1) %>% set_engine("glmnet")

 linreg_lasso_workflow <- workflow() %>% add_model(linreg_lasso) %>% add_recipe(bmi_recipe)
 
linreg_lasso_fit_workflow <- linreg_lasso_workflow %>% fit(tb_train)

linreg_lasso_fit_workflow
```

```{r}
lambdas <- linreg_lasso_fit_workflow %>% 
  extract_fit_engine() %>% .$lambda

lasso.pred <- linreg_lasso_fit_workflow %>% 
  predict(tb_val, penalty=lambdas[60])

lasso.pred
```



```{r}

linreg_ridge <-  linear_reg(penalty = tune(), mixture = 1) %>% set_engine("glmnet")

 
 linreg_ridge_workflow <- workflow() %>% add_model(linreg_ridge) %>% add_recipe(bmi_recipe)
 
linreg_ridge_fit_workflow <- linreg_ridge_workflow %>% fit(tb_train)

linreg_ridge_fit_workflow
```




```{r}
# Hypothesis testing
# mu(stroke) = mu(no stroke) of bmi, glucose, age ? 


age_stroke <- tb_train %>% filter(stroke==1) %>% select(age)

age_stroke_mean <- mean(age_stroke[['age']])


age_no_stroke <- tb_train %>% filter(stroke==0) %>% select(age)

age_no_stroke_mean <- mean(age_no_stroke[['age']])

age_no_stroke_mean
```



